#!/bin/sh
# 更新yum
  yum update -y
# 安装GIT
  yum install git -y
# 安装Docker
  yum install docker -y
# 设置开机默认启动Docker
  systemctl enable docker
# 安装Docker-Compose依赖
  yum install python-pip -y
# 检测是否存在Docker-Compose包
  pip uninstall docker-compose -y
# 安装Docker-Compose
  pip install docker-compose -y
# 从GitHub拉取Docker自动构建Redis,MySQL,Nginx的库
  git clone https://github.com/Goular/DockerModule.git /drnmp
# 删除git库，避免影响www文件夹其他代码的git clone
  cd /drnmp
  rm -rf .git
# 退出脚本
#  exit 0
